[features]
seeds = false
skip-lint = false

[programs.localnet]
#unique_id = "u7X6Ut4Mm9wqQ8ci2XiUjtcyqRJnHScStUo81Deh6bA"
#spl_4626_vault="987M4VVtt2T3bHBV6cXmeMsZgAxbMs2HUBaaAcpqFeyW"
simple_vault="DGXrmuhPvYJEWytSpZPB3PCA2zNvSsNvctkAeS924473"
unique_low="ACM92DSXA9ebVyxQpZf4EKDvuEgXsiAkD6Us8kTcGVh7"
test_token="BSCgQLPHjjvoH6qbG59dyxUTfcK6jAqFDdPk6MNN7sEz"

[programs.testnet]
#unique_id_nft = "u7X6Ut4Mm9wqQ8ci2XiUjtcyqRJnHScStUo81Deh6bA"
#spl_4626_vault="987M4VVtt2T3bHBV6cXmeMsZgAxbMs2HUBaaAcpqFeyW"
simple_vault="DGXrmuhPvYJEWytSpZPB3PCA2zNvSsNvctkAeS924473"
unique_low="ACM92DSXA9ebVyxQpZf4EKDvuEgXsiAkD6Us8kTcGVh7"
test_token="BSCgQLPHjjvoH6qbG59dyxUTfcK6jAqFDdPk6MNN7sEz"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "testnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
nft_init = "ts-node -T migrations/initNFTCollection.ts"

token_init = "ts-node -T migrations/initTestToken.ts"
find_token = "ts-node -T migrations/findTokenMint.ts"
init_vault = "ts-node -T migrations/initVault.ts"

check_vault = "ts-node -T migrations/checkVault.ts"
close_vault = "ts-node -T migrations/closeVault.ts"

[test]
startup_wait = 10000

[test.vault_full]
startup_wait = 10000